### ISSUE TITLE
Opensearch Support

### ISSUE THREAD

**Issue by JMoserCricut** [crossplane-contrib/provider-aws#1228]
### What resource do you need?
OpenSearch (formerly ElasticSearch)
https://aws.amazon.com/opensearch-service/the-elk-stack/what-is-opensearch/

### What is your use case?
This is one of the last use cases needed for our workloads' infrastructure needs in order to have a complete crossplane adoption. One of it's current uses is as a caching layer in front of mongodb datastore.

### Would you be willing to contribute it using [code generator](https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md)?
I can try in my free time, although I've not worked in GO yet. 

Opening this request based on suggestion found in this issue:
https://github.com/crossplane/provider-aws/issues/238#issuecomment-1073776452

@haarchri @sqerison

**Comment by sendmars** [comment]
Hi team,

I started with this by using the code generator and ran into two issues:

1) Opensearch has a resource called `Package` which refers to [custom packages](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/custom-packages.html) for dictionaries, synonyms, etc. When running `make services SERVICES=opensearch`, `goimports` fails because `pkg/controller/opensearch/package/*` have `package package` statement (using a keyword as an identifier). My workaround is to ignore this resource for now by adding it to the ignore list of `generator-config.yaml`. I'm able to proceed.

2) When I run `make generate`, it fails on unrecognized package names `opensearch` and `opensearchiface`:

```
go: downloading github.com/aws/aws-sdk-go v1.44.7
github.com/crossplane/provider-aws/pkg/controller/opensearch/domain imports
        github.com/aws/aws-sdk-go/service/opensearch: module github.com/aws/aws-sdk-go@latest found (v1.44.7), but does not contain package github.com/aws/aws-sdk-go/service/opensearch
github.com/crossplane/provider-aws/pkg/controller/opensearch/domain imports
        github.com/aws/aws-sdk-go/service/opensearch/opensearchiface: module github.com/aws/aws-sdk-go@latest found (v1.44.7), but does not contain package github.com/aws/aws-sdk-go/service/opensearch/opensearchiface
```

The problem here is inconsistent naming in [aws-sdk-go](https://github.com/aws/aws-sdk-go/tree/v1.44.7/service/opensearchservice), where the service is `opensearchservice` and not `opensearch` as specified in the api. The reference to `opensearch` and `opensearchiface` is in `pkg/controller/opensearch/domain/zz_controller.go`.

A quick glance on apis and services in aws-sdk-go shows that names match, so this may be a unique issue. Do you have a suggestion how best to proceed?

**Comment by sendmars** [comment]
I set the service name to `opensearchservice` and declared in `apis/opensearchservice/generator-config.yaml`:

```yaml
model: opensearch
```

This is based on the approach for prometheusservice, thanks to @haarchri to pointing this out in the Crossplane slack channel. `make generate` completes so I'm continuing on to the next steps.

**Comment by sendmars** [comment]
I ran into an issue with `Observe` for Opensearch for a Domain resource. `Observe` is part of the generated `zz_controller.go`.

It calls `e.client.DescribeDomainWithContext(ctx, input)`. Input contains `DomainName: test-domain`.

`DescribeDomainWithContext` is a method in [aws-sdk-go](https://github.com/aws/aws-sdk-go/blob/main/service/opensearchservice/api.go#L1148). It makes a rest api call to the Opensearch service:

```
*net/http.Request {
  Method: "GET",
  URL: *net/url.URL {
    Scheme: "https",
    Opaque: "",
    User: *net/url.Userinfo nil,
    Host: "es.us-west-2.amazonaws.com",
    Path: "/2021-01-01/opensearch/domain/test-domain",
    RawPath: "/2021-01-01/opensearch/domain/test-domain,
    ForceQuery: false,
    RawQuery: "",
    Fragment: "",
    RawFragment: ""
  },
  ...
}
```

and receives an answer that the domain is not found in this format (**response format is important here**):

```
error(*github.com/aws/aws-sdk-go/aws/awserr.requestError) *{
  awsError: github.com/aws/aws-sdk-go/aws/awserr.awsError(*github.com/aws/aws-sdk-go/aws/awserr.baseError) *{
    code: "DBClusterNotFoundFault",
    message: "DBCluster dom-test-external-1 not found.",
    errs: []error len: 0, cap: 0, nil
  },
  statusCode: 404,
  requestID: "67715bd5-3dd6-43d9-bdbc-fc29626e4ffe",
  bytes: []uint8 len: 0, cap: 0, nil
}
```

`zz_controller.go` then checks if the error can be ignored by passing the error to the ignore method:

```
return managed.ExternalObservation{ResourceExists: false}, awsclient.Wrap(cpresource.Ignore(IsNotFound, err), errDescribe)
```

`zz_conversions.go` handles the error with this part of code. It would be happy to return the here if it can recognize the error message in `awsErr.Code`. **Neither the error message, nor the path `awsErr / Code` don't exist in the error response above.**

```
func IsNotFound(err error) bool {
	awsErr, ok := err.(awserr.Error)
	return ok && awsErr.Code() == "UNKNOWN"
}
```

I compared this with:
* Rds DBCluster - It contains the correctly formatted response and `IsNotFound` error code matches the received message.
* CloudWatch LogGroups - `IsNotFound` is the same, but in my attempt to create a LogGroups, it doesn't error, because the request issued by `aws-sdk-go` is to list all loggroups and not look for a specific loggroup, so it didn't even fail.

I need some guidance from the community or Crossplane team to understand what my options are to unblock this. My understanding is that I shouldn't change `zz_*` files, which would be one way forward.

**Comment by haarchri** [comment]
@sendmars sorry for late answer
Checkout https://github.com/crossplane-contrib/provider-aws/blob/master/apis/kafka/generator-config.yaml#L13 you can specify the errorCode and rerun generation

**Comment by mvkrishna86** [comment]
Hi, in our environment we are using RDS, MSK, ElastiCache and Opensearch. I am able to create everything using crossplane except opensearch. Any idea when can I expect this to be available in main branch?
