### ISSUE TITLE
AWS_PROFILE and ~/.aws/credentials

### ISSUE THREAD

**Issue by joebowbeer** [crossplane-contrib/provider-aws#1439]
### What problem are you facing?

Please enhance the aws ProviderConfig to support [sources other than access_key and secret_key environment variables](https://www.padok.fr/en/blog/authentication-aws-profiles)

The Terraform provider, for comparison, can obtain creds given only an AWS_PROFILE, provided that it can locate the shared credentials file (and shared configuration file for non-default profiles).

https://registry.terraform.io/providers/hashicorp/aws/latest/docs#authentication-and-configuration

This way, creds managers like [Leapp](https://www.leapp.cloud/) can work seamlessly with Terraform:

https://blog.pethron.me/how-to-access-aws-and-azure-in-terraform

### How could Crossplane help solve your problem?

If Crossplane could consume only AWS_PROFILE then it would be possible to use a creds manager like Leapp to refresh the short term credentials.

What I am looking for is support for AWS_PROFILE in local clusters without [IRSA](https://github.com/crossplane-contrib/provider-aws/blob/master/AUTHENTICATION.md#using-iam-roles-for-serviceaccounts). (I assume IRSA is not an option for local clusters; please correct me if I'm wrong.)

While I have lots of use cases for IRSA in EKS, my use cases motivating this request for AWS_PROFILE are local testing, development and bootstrapping.

I would like to use a credential manager (e.g. Leapp, aws-vault?) to obtain short-term creds and refresh them as needed.

When I see the same `secret_key` / `access_key` instructions and custom scripts pasted into a half dozen articles and tutorials, I can't help thinking there's a better way that might benefit others.

In `kind`, you can mount `~/.aws` to each worker node (container) and the AWS_SDK (called by the pod) can then use that to assume the role based on AWS_PROFILE.

Originated at https://github.com/crossplane/crossplane/discussions/3246

**Comment by haarchri** [comment]
think we have a few Options:

https://github.com/crossplane-contrib/provider-aws/blob/master/examples/providerconfig/fs.yaml

https://github.com/crossplane-contrib/provider-aws/blob/master/examples/providerconfig/none.yaml


IRSA for local environments: https://blog.amis.com/aws-irsa-for-self-hosted-kubernetes-e045564494af

other Option is IAM Roles Anywhere https://aws.amazon.com/de/blogs/security/extend-aws-iam-roles-to-workloads-outside-of-aws-with-iam-roles-anywhere/ - but never tried it because it's new
