### ISSUE TITLE
Add EventBridge resources

### ISSUE THREAD

**Issue by spolve** [crossplane-contrib/provider-aws#1477]
### What resource do you need?
EventBridge: 
- Archive
- APIDestination
- EventBus
- Connection
- EventSource 

### What is your use case?
Use EventBridge features as a main event queue for our new micro service architecture; I need all feature of EventBridge.

### Would you be willing to contribute it using [code generator](https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md)?
I've tried with the base generation, but I don't know which fields is a custom field and needs a custom implementation for *Ref and *Selector.

**Comment by taylorsmithgg** [comment]
Any updates on this?

**Comment by taylorsmithgg** [comment]
FYI for anyone still following this, the upbound provider does have support for crossplane resources:
https://marketplace.upbound.io/providers/upbound/provider-aws/v0.38.0/resources/cloudwatchevents.aws.upbound.io/Rule/v1beta1

**Comment by taylorsmithgg** [comment]
/fresh Is there any plan to continue supporting this provider as opposed to upbound?

**Comment by MisterMX** [comment]
> Is there any plan to continue supporting this provider as opposed to upbound?

This provider is maintained by the community only. We plan to provide continues support for it. However, due to the limited amount of maintainers and time we will focus on bugfixes and refactoring to keep the code clean and ensure it works. We wont add support for new resources on our own but we are open for pull requests to add new functionality to it.
