### ISSUE TITLE
Provider error logs not visibile

### ISSUE THREAD

**Issue by ivankatliarchuk** [crossplane-contrib/provider-aws#1588]
### What problem are you facing?
Currently, the only way to identify if there are any operational errors that crossplane aws provider facing is to turn on DEBUG logging. Debug logging is verbose and is in non-json format.

Debug is off
![Screenshot 2022-11-21 at 14 26 01](https://user-images.githubusercontent.com/5395690/203747983-673c87cd-d62d-4304-9c40-626ab5789cde.png)
Debug is On for same provider

![Screenshot 2022-11-21 at 14 25 37](https://user-images.githubusercontent.com/5395690/203748739-49de97a6-ceee-43a3-99eb-fd7b6b8ddeff.png)

For some reason `cannot create` only visible when debug flag is set, when clearly it should be an `Error`. 
My understanding, by design `Debug` logs do support only plain text, as well as not something that should be used in production.

![Screenshot 2022-11-21 at 14 12 33](https://user-images.githubusercontent.com/5395690/203750179-e7fbb303-e46d-44d1-8056-3cf704c13d05.png)

### How could Crossplane help solve your problem?
- Messages like `cannot create` and similar to be visible and have correct `Error` log level
- Errors visible without `--debug` flag
- Errors without `--debug` to be in `json` format by default

**Comment by haarchri** [comment]
think you can see the error in events on the resource level ?

**Comment by ivankatliarchuk** [comment]
I might be missing something. Is this a feature e.g. not to stdout error logs? On which resource I should be able to see this error e.g. what the kubectl command by any chance and why debug and info level logging have such a different behaviour?

**Comment by rkoalign** [comment]
> think you can see the error in events on the resource level ?

@haarchri Most of the times we see errors in resource level events, however sometimes if the managed resource object itself is not created by provider-aws/crossplane for some reason, then we cannot see such resource level events because no resource exists yet. For example, our composite resource should create, among others, an AWS KMS Key Alias as a managed resource, however for some unknown (yet) reasons, we don't see a resource in our K8s cluster under `alias.kms.aws.crossplane.io` resource types. There are no events related to this to indicate why crossplane/provider-aws couldn't create it, not even in the associated composite resource (or claim).

There are no logs in provider-aws indicating successful or failed attempts. I think the only way to know in this scenario is to enable debug logging in provider-aws.

**Comment by haarchri** [comment]
Then you need crossplane core debug If the resources is created out of compositions not provider level

**Comment by rkoalign** [comment]
Yes thank you, debug logs of provider-aws did not indicate any problem I mentioned in my previous comment, but those of crossplane core did in fact show my problem. However, the original point in this issue probably still holds true - that debug logging had to be enabled to get a failure/error message.

**Comment by ivankatliarchuk** [comment]
^ Correct. This is fundamentally wrong behaviour. `info` level logging should not swallow any `error` level logging. Debug level is way too noisy and every log ingestion do cost resources.
