### ISSUE TITLE
Certificate resources do not include ResourceRecords in status for SANs

### ISSUE THREAD

**Issue by jutley** [crossplane-contrib/provider-aws#1697]
### What happened?

I haven't actually tried using Certificate resources yet. I am just reading the docs and noticed that the Certificate kind's status only contains room for a single resourceRecord field. As mentioned in the conversation in #807, a certificate will have a domain validation record for the certificate's domain name as well as each SAN in the certificate.

The certificate's `DomainValidationOptions` field is an array, but as seen in the code, only the first element is used.

https://github.com/crossplane-contrib/provider-aws/blob/master/pkg/clients/acm/certificate.go#L78

I'll also note that I would be interested in making a contribution here, but this is a breaking API change. Guidance here would be appreciated. We can possibly make a new field with all challenges and leave the existing one in place. It is ugly but backwards compatible that way.

### How can we reproduce it?

If you create a certificate that includes SANs, you will not see their validation records in the status.

### What environment did it happen in?
provider-aws version: v0.37.1

**Comment by MisterMX** [comment]
While this is indeed a breaking change, it should not be a big problem since it is only status information that changes. It should be straightforward to the change the property to an array and have it contain all information given by AWS.

@jutley you are very welcome to work on this! Once you have something just open a PR and assign me as a reviewer :)
