### ISSUE TITLE
SNS/Topic policy not applied by aws provider in crossplane

### ISSUE THREAD

**Issue by mihaelabalas84** [crossplane-contrib/provider-aws#1896]
Given the following manifest, AWS provider in Crossplane does not apply the policy. Instead, it creates a Topic with the default policy.

```
apiVersion: sns.aws.crossplane.io/v1beta1
kind: Topic
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-50'
  labels:
    app.kubernetes.io/instance: demo-application-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fairmoney-base-chart
    argocd.argoproj.io/instance: demo-application-dev
    fairmoney.io/application: demo-application
    helm.sh/chart: fairmoney-base-chart-0.1.0
  name: fairmoney-dev-demo-application-uploads
spec:
  deletionPolicy: Delete
  forProvider:
    name: fairmoney-dev-demo-application-uploads
    policy: |
      {
        "Version": "2008-10-17",
        "Statement": [
          {
            "Sid": "AllowPublishFromS3",
            "Effect": "Allow",
            "Principal": {
              "Service": "s3.amazonaws.com"
            },
            "Action": "sns:Publish",
            "Resource": "arn:aws:sns:eu-west-1:027159582536:fairmoney-dev-demo-application-uploads",
            "Condition": {
              "ArnLike": {
                "aws:SourceArn": [
                    "arn:aws:s3:*:*:fairmoney-dev-demo-application"
                ]
              }
            }
          }
        ]
      }
    region: eu-west-1
```
**Workaround:** adding or modifying the displayName parameter will also apply the policy.

**Comment by MisterMX** [comment]
It seems the policies were not compared in a structural manner but only by plain string comparison. Also, the policy was apparently not added to the update attributes correctly.

**Comment by offzale** [comment]
@MisterMX thanks a lot for fixing this! the aws provider was trying to update the policies of all the topics managed by crossplane all day long before. the diff is performed correctly now 🙌 

I was wondering if the same might be happening to sqs queues' **policies**, topic subscriptions' **filterPolicies**, and s3 buckets **ownershipControls** and **bucketEncryption**. Because the same that was happening before your fix to the sns policies has been happening to me with those other resources' settings as well. So the AWS APIs are getting hammered by the provider trying to update those settings non stop with no reason.
