### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by dudicoco** [crossplane-contrib/provider-aws#1954]
How does the release of the [new upbound aws provider](https://blog.upbound.io/first-official-providers) affect this project?

The official docs now direct users to use the ubound provider, which means there will be less and less usage of this provider over time.
It is confusing for users to understand why there are two different aws providers (personally I had to dig in to figure this out) and which one they should choose.

What does the future hold for this project? Is there a reason for it to live side by side with the upbound provider instead of joining forces on a single provider?

**Comment by jonashackt** [comment]
The same question occured to me. Looking from the outside onto the project, this is really confusing. Additionally the [community Azure provider](https://github.com/crossplane-contrib/provider-azure) and the [community GCP provider](https://github.com/crossplane-contrib/provider-gcp) don't seem to be in active development any more (last release +1 year ago).

**Comment by MisterMX** [comment]
A short statement to clarifiy the status and future of this repository:

Upbound has moved to its own Terraform-based set of providers. This means that https://github.com/crossplane-contrib/provider-aws is now only maintained by community volunteers since there is a number of people out there who are still using it.

It is kind of legacy but it will receive further updates as long as the community is willing to contribute to it. Due to the limited number of active maintainers - two at the time of writing - there is no capacity to implement new controllers. So all issues labeled as `enhancement` will most likely not be treated by us. However, we do accept PRs for new features or bug fixes.

Since the core resources (IAM, RDS, S3 etc.) are pretty much matured it should be safe to continue with this provider should your Crossplane platform already run with it. For new projects we recommend to use https://github.com/upbound/provider-aws as we project a better long-term support for it.

I hope that cleared things up a bit.

BTW: If someone is willing to become a maintainer for this repository, feel free to send me a PM on [Crossplane Slack](crossplane.slack.com).

**Comment by dudicoco** [comment]
Thanks for the info @MisterMX.

I believe it would be beneficial to include this information in the repo's readme.

**Comment by drewhemm** [comment]
> Thanks for the info [@MisterMX](https://github.com/MisterMX).
> 
> I believe it would be beneficial to include this information in the repo's readme.

This should absolutely be in the repo's readme. I learned about this project's status and found this issue due to an answer from Google Gemini...
