### ISSUE TITLE
DynamoDB: Add PointInTimeRecoveryEnabled

### ISSUE THREAD

**Issue by duncaan** [crossplane-contrib/provider-aws#488]
### What problem are you facing?
There is no way to set the PointInTimeRecoveryEnabled value on a dynamodb table or backup.  This is possible through the AWS SDK: https://docs.aws.amazon.com/sdk-for-go/api/service/dynamodb/#PointInTimeRecoverySpecification

### How could Crossplane help solve your problem?
Allow the dynamodb table or backup CRD to allow setting PointInTimeRecoveryEnabled to true or false

**Comment by duncaan** [comment]
Looked a little deeper and seems that the PITR was enabled with this PR: https://github.com/aws/aws-sdk-go/pull/1864/files but unsure why it isn't being generated by https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md

**Comment by duncaan** [comment]
@muvaf - Is this anything you might know about?

**Comment by hasheddan** [comment]
@duncaan looks like this field is not generated because it can't actually be set at table creation (https://docs.aws.amazon.com/sdk-for-go/api/service/dynamodb/#CreateTableInput). We will likely need to add a `ContinuousBackups` resource as a standalone type that references a `Table` object, or incorporate it into the table spec https://docs.aws.amazon.com/sdk-for-go/api/service/dynamodb/#UpdateContinuousBackupsInput

**Comment by jdfalk** [comment]
It seems like this would be pretty easy to implement if you do something like you do in the security groups. Can something like that be implemented, where you make two calls one immediately after the other on create?

https://github.com/crossplane/provider-aws/blob/97f0753230fbe2de63d234364827178d5ec1876f/pkg/controller/ec2/securitygroup/controller.go#L180

**Comment by muvaf** [comment]
We can have this `PointInTimeRecoverySpecification` struct in `CustomTableParameters` and make the ` UpdateContinuousBackups` call in `setup.go` during `Update`.
