### ISSUE TITLE
Rename RDSInstance to DBInstance in rds group

### ISSUE THREAD

**Issue by muvaf** [crossplane-contrib/provider-aws#498]
### What problem are you facing?

We've had the convention of sticking to the cloud provider SDK when we name the resources and groups. But since `RDSInstance` is one of the oldest CRD, it stayed as `RDSInstance` in the `database.aws.crossplane.io` group. Now that we have ACK code generation, it's not only a convention but a technical requirement. For example, ACK [puts](https://github.com/crossplane/provider-aws/pull/489) `DBCluster` in `rds.aws.crossplane.io`. However, other elements of RDS service, like `DBSubnetGroup` or `RDSInstance` are still in `database.aws.crossplane.io`. 

### How could Crossplane help solve your problem?

We can move `RDSInstance` to `rds.aws.crossplane.io` and rename it to how it appears, i.e. `DBInstance`. However, since it's a [`v1beta1` level resource](https://kubernetes.io/docs/reference/using-api/#api-versioning), we either need to automatically handle the migration or provide step by step instructions.

Since it's a rename, I don't think we can use CRD webhooks since they are meant for version upgrades, not renames. So, I suggest that we have two CRDs and two controllers, completely separate, for each and mark `RDSInstance` as deprecated. We can keep it for a while but future improvements would be on the `DBInstance` one.

**Comment by negz** [comment]
Can we duplicate the RDSInstance implementation (i.e. types and controller) as DBInstance to begin with? This would create a manual migration path without us having to automate it.

**Comment by muvaf** [comment]
@negz Yes, that's what I had in mind, too. We can use ACK to generate `DBInstance` and fill up the custom parts with the existing code in `RDSInstance`

**Comment by muvaf** [comment]
We can fix https://github.com/crossplane/provider-aws/issues/519 as well in the new `DBInstance` type.

**Comment by petteja** [comment]
It is confusing that we still have both RDSInstance and DBInstance. Both are getting new features, but mostly they're not implemented in both, so they diverge more and more. Any plans to move forward with this issue?

**Comment by ascar73** [comment]
Looking for clarification here, please, @negz.  
Is the intent to deprecate [database.aws.crossplane.io/v1beta1, kind: RDSInstance](https://doc.crds.dev/github.com/crossplane/provider-aws/database.aws.crossplane.io/RDSInstance/v1beta1@v0.28.1) so that [rds.aws.crossplane.io/v1alpha1, kind: DBInstance](https://doc.crds.dev/github.com/crossplane/provider-aws/rds.aws.crossplane.io/DBInstance/v1alpha1@v0.28.1) is the go-forward resource?
If yes: 
1) when will it be marked `deprecated` so that we (and others) opt to not use it and 
2) how do we prioritize this to eliminate further divergence as @petteja notes above?
If no, please help me understand what the intended solution is.  
Thanks!
