### ISSUE TITLE
Annotate CRDs with information about what IAM permissions needed to reconcile

### ISSUE THREAD

**Issue by muvaf** [crossplane-contrib/provider-aws#514]
### What problem are you facing?

The controllers need permissions to make calls to AWS API but it's hard to figure out what permissions a specific controller needs to work properly. For example, if I use only S3 CRD, I want to limit the IAM User I use to the calls that can ever be made by S3 controller.

### How could Crossplane help solve your problem?

We can write a small Go program that scans `pkg/controller/*` folders for AWS calls they make and annotate the respective CRDs. It can be part of our `make generate` target after kubebuilder generates the CRD YAMLs.

The tool would likely be provider-specific.

**Comment by jack1902** [comment]
This would be extremely useful to be able to state `resource x` requires permissions y. For example, in order to define an `rds` resource you'll need describe, delete, create etc for the IAM role attached.

Laborious i know, but being able to know exactly what permissions would be needed for each CRD defined for the `provider-aws` would make it far easier to use (terraform is really frustrating in this area, as you have to figure it out everytime)
