### ISSUE TITLE
NodeGroup IMDSv2 support

### ISSUE THREAD

**Issue by ryneal** [crossplane-contrib/provider-aws#821]
### What problem are you facing?
It is not possible to set IMDSv2 for EC2 instances created by NodeGroup, it currently defaults to IMDSv1.

### How could Crossplane help solve your problem?

Requesting parameters added to CRD to configure IMDSv2 on NodeGroup EC2 instances.

**Comment by chlunde** [comment]
I think this requires launch templates, which is this issue: https://github.com/crossplane/provider-aws/issues/338
It should be possible to implement this now since AWS SDK for Go v2 has been updated. 

LaunchTemplateData.MetadataOptions.HttpTokens -> required
LaunchTemplateData.MetadataOptions.HttpPutResponseHopLimit -> 1
