### ISSUE TITLE
Crossplane should provide the actual state of the resource

### ISSUE THREAD

**Issue by vinsguru** [crossplane-contrib/provider-aws#840]
I create a Bucket in aws using crossplane with the following spec. I see the bucket created bucket successfully.

```
spec:
  forProvider:
    acl: private
    locationConstraint: us-west-2
    objectLockEnabledForBucket: false
```

`kubectl describe bucket` provides the following information.
```
Spec:
  Deletion Policy:  Delete
  For Provider:
    Acl:                             private
    Location Constraint:             us-west-2
    Object Lock Enabled For Bucket:  false
```
Now i intentionally change the `objectLockEnabledForBucket: true` and re-apply to modify the resource. ( I do understand that AWS does not allow us to change the object lock once the bucket is created.)

I get the confirmation on the console that it is `configured`.

`kubectl describe bucket` provides the following information. But AWS shows that object lock is disabled.

```
 Spec:
  Deletion Policy:  Delete
  For Provider:
    Acl:                             private
    Location Constraint:             us-west-2
    Object Lock Enabled For Bucket:  true
```

**_Actual Behavior:_**

- Crossplane does not show the actual state of the resource. 

**_Expected Behavior:_**

- The state of the bucket resource should match with what we have in AWS.

**Comment by haarchri** [comment]
@vinsguru did you checked status.atProvider ?

**Comment by MisterMX** [comment]
Closing this as this issue is stale an no provider bug is visible from the information above.

Please check the status of the bucket as well as the emitted events. If an error happens, that is usually emitted as a warning event.

Also note that the spec is not necessarily the state of the object, but rather the desired configuration. If the external bucket is different, the provider will try to update it.
